language: java
jdk:
- oraclejdk8
sudo: false
env:
  matrix:
  - MC=1.13
git:
  submodules: false
notifications:
  email: false
before_install:
- sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
- git submodule update --init --recursive
- cd uSkyBlock-Core/src/main/po && perl en2pirate.pl && cd -
- cd uSkyBlock-Core/src/main/po && perl en2kitteh.pl && cd -
install:
- mvn -nsu -Dtravis.buildNumber=${TRAVIS_BUILD_NUMBER} -Pi18n,${MC},we700,wg700 install
