/*
 * This file was generated by the Gradle 'init' task.
 */


dependencies {
    implementation("org.jetbrains:annotations:23.0.0")
    compileOnly("io.papermc.paper:paper-api:26.1.2.build.+")
}

group = "com.github.rlf"
description = "uSkyBlock-API"

