/*
 * This file was generated by the Gradle 'init' task.
 */


dependencies {
    implementation("org.jetbrains:annotations:23.0.0")
    compileOnly("io.papermc.paper:paper-api:1.21.11-R0.1-SNAPSHOT")
}

description = "uSkyBlock-APIv2"

